---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86176.
--- DateTime: 2022/12/5 22:39
---


-- Lua 中的简单变量类型。
-- nil number string boolean
-- Lua 中所有变量的定义都不需要定义变量类型，他会自动判断类型。
-- 类似 C# 里面的 var
-- Lua 中的一个变量可以随便赋值（自动识别类型）

-- lua 中使用没有声明过的变量，不会报错默认值是 nil。
print(a);

-- 通过 type 函数，返回值是string，我们可以得到变量的类型。
a = false;
print(type(a));
print(type(type(a)));

-- nil 有点类似 C# 中的 null。
a = nil;
print(a);

-- number 所有数值都是 number。
a = 1.3;
print(a);

-- string 字符串的声明，需使用单引号或双引号包裹。
a = "999String";
print(a);

-- boolean 就是 C# 中的 bool。
a = true;
print(a);