---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86176.
--- DateTime: 2022/12/6 20:55
---

-- 单分支。
if 1 < 2 then
    print(true);
end

-- 双分支。
if 1 > 2 then
    print(true);
else
    print(false);
end

-- 多分支（lua 中没有 switch 分支语句）。
if 1 > 2 then
    print("1 > 2");
elseif 1 == 2 then
    print("1 == 2");
elseif 1 >= 2 then
    print("1 == 2");
else
    print("1 < 2");
end

-- 组合条件分支。
if 1 <= 2 and 1 > 0 then
    print("1 <= 2 && 1 > 0");
end