---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86176.
--- DateTime: 2022/12/9 19:57
---

-- 全局变量与本地变量
variableGlobal = "全局变量，比较浪费内存，尽量使用局部变量";
local variableLocal = "局部变量";
print(variableGlobal);
print(variableLocal);

-- 多脚本执行（require 可以执行另外一个脚本 require(同一目录下传入脚本名即可，不同路径下需要给路径和脚本名)）
require("009_ComplexDataType");
Student:Speak3();

-- 脚本卸载（package.loaded["脚本名"] 返回值是 boolean 意思是该脚本是否被执行）

-- 如果脚本被 require 加载过一次，之后的 require 是不会再被执行。
require("009_ComplexDataType");

if package.loaded["009_ComplexDataType"] then
    package.loaded["009_ComplexDataType"] = nil;
end

-- require ：脚本的最后可以 return 一个外部希望获取的内容一般情况是一个局部变量。
local testLocal = require("009_ComplexDataType");
print("接收到其他脚本返回过来的变量：" .. testLocal);

-- 大 G 表（是一个总表（table）,它将所有声明的全局变量都储存在其中）
for key, value in pairs(_G) do
    print(key, value);
end