---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86176.
--- DateTime: 2022/12/9 21:15
---

-- 多变量赋值
local a, b, c = 1, 2, "3";
print(a, b, c);

a, b, c = 1, "2";
print("多变量赋值，给的参数不够自动补空 " .. a, b, c);

a, b, c = 1, "2", 3, "4";
print("多变量赋值，给的参数多了自动省略 " .. a, b, c);

-- and or （不仅可以用来连接 boolean 任何东西都可以用来连接）
-- 在 lua 中，只有 nil 和 false 才认为是假
-- ”短路“ 对于 and 来说有假则假，对于 or 来说有真则真
-- 所以他们只需要判断第一个是否满足就会停止计算了
print(false and true);
print(0 and 1);
print(nil and false);
print(true and 1);

print(false or true);
print(false or 1);
print(1 or true);
print(false or nil);

-- lua 不支持三元运算符，但是可以自己写
-- 1 小于 2 返回结果为 true 然后 or 是有真则真这里比较的就是，前面结果 true 和 2 比较，所以返回 true 因为它只需要判断第一个是否满足。
print((1 < 2) and 1 or 2);