---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86176.
--- DateTime: 2022/12/13 19:46
---

-- 时间
print(os.time());
print(os.time({ year = 2022, month = 12, day = 13 }));

local nowTime = os.date("*t");
for k, v in pairs(nowTime) do
    print(k, v);
end
print(nowTime.hour);

-- 数学运算
print("绝对值 ：" .. math.abs(-11));
print("弧度转角度 ：" .. math.deg(math.pi));
print("三角函数传弧度 ：" .. math.cos(math.pi));

print("向下整取 ：" .. math.floor(2.6));
print("向上整取 ：" .. math.ceil(2.6));

print("最大值 ：" .. math.max(2, 3));
print("最小值 ：" .. math.min(2, 3));

-- 小数分离，分成整数和小数两部分
print(math.modf(1.2));

-- 随机数
math.randomseed(os.time());
print("这个随机数受到随机种子的影响 ：" .. math.random(100));
print(math.random(100));

-- 开方
print(math.sqrt(4));

-- lua 脚本加载路径
print(package.path);
package.path = package.path .. ";C:\\";
print(package.path);