---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86176.
--- DateTime: 2022/12/16 11:44
---

test = { id = 1, name = "123" };

-- 垃圾回收（collectgarbage）

-- 获取当前 lua 占用内存数 K 字节用返回值 *1024 就可以得到具体的内存占用字节数
print(collectgarbage("count"));

-- lua 中的机制和 C# 中垃圾回收机制很类似，解除羁绊就是变垃圾
test = nil;

-- 进行垃圾回收，理解有点像 C# 的 GC
collectgarbage("collect");

print(collectgarbage("count"));

-- lua 中有自动定时进行 GC 的方法
-- Unity 中热更新开发，尽量不要去用自动垃圾回收